### ISSUE TITLE
Doesn't work on arm64

### ISSUE THREAD

**Issue by tomatau** [kimschles/pod-info-app#1]
Following the linkedin course I was hitting `CrashLoopBackoff`, inspect the logs to find `exec /usr/local/bin/docker-entrypoint.sh: exec format error`

Turns out this image doesn't work on new MacBooks, it needs to be built for more than one platform

```
➜ docker run kimschles/pod-info-app:latest
Unable to find image 'kimschles/pod-info-app:latest' locally
latest: Pulling from kimschles/pod-info-app
1efc276f4ff9: Pull complete
189059254212: Pull complete
ffaf71e5f813: Pull complete
27dd1c85eb27: Pull complete
b67794d9d8ee: Pull complete
d08f8415b4d8: Pull complete
40a6bad6358d: Pull complete
ae1edb75b21d: Pull complete
92fae04c81df: Pull complete
63a29c15ea29: Pull complete
Digest: sha256:0feb76f0445f658b727f33aaadd72c8afe03c69a08cff8bb110ac66c48a7a9ba
Status: Downloaded newer image for kimschles/pod-info-app:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /usr/local/bin/docker-entrypoint.sh: exec format error
```

**Comment by brianstrauch** [comment]
I pushed an ARM64-compatible image to my DockerHub, so anyone who's interested in running this tutorial on ARM64 can update the "image" field in deployment.yaml.
```
image: bstrauch24/pod-info-app:latest
```

It would be great if @kimschles could push a multi-platform image!

**Comment by s1onez** [comment]
same for me, can't run on rockchip

**Comment by kimschles** [comment]
Hey @brianstrauch, @tomatau and @s1onez. 

I just pushed a multi-platform image to Docker Hub. You can see it here: https://registry.hub.docker.com/r/kimschles/pod-info-app/tags

Thanks for bringing this to my attention!
